---
title: "iNaturalist_vs_Twitter"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
lazyLoad = TRUE
#packages - use devtools or remotes for github versions
library(here)
library(rtweet)
library(sp)
library(sf)
library(data.table)
library(plyr)
library(rgdal)
library(raster)
library(rgeos)
library(maps)
library(maptools)
library(rmapshaper)
library(ggplot2)
library(ggspatial)
library(ggthemes)
library(ggsn)
library(dplyr)
library(extrafont)
library(spatialEco)
#here::set_here("tweet_distribution_comparison")
here::here()
options(digits=5)
```

```{r update}
#update all packages - optional
update.packages()
```

```{r read}
#read
spider_tweets_sentiment <- read_twitter_csv(here::here("R_files_Twitter", "data", "spiders06062020BIGsentiment.csv"), unflatten = FALSE)
obsperstate <- read.csv(here::here("R_files_distribution", "obsperstate.csv"))
speciesperstate <- read.csv(here::here("R_files_distribution", "speciesperstate.csv"))
```

```{r mapobservations}
#WGS84
WGS84_proj = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
#copy counts
usa_basemap <- getData('GADM', country='USA', level=1)
usa_basemap@data$stateinUSA <- usa_basemap@data$NAME_1
usa_basemap@data <- join(usa_basemap@data, obsperstate, type="left")
usa_basemap@data$obsNA <- is.na(usa_basemap@data$obscount)
for(i in 1:nrow(usa_basemap@data)) {
  if(usa_basemap@data$obsNA[i] == "TRUE"){
  usa_basemap@data$obscount[i] <- "0"
  }
  else
  {
    i+1
  }
}
#group counts
usa_basemap@data$obscount <- as.numeric(usa_basemap@data$obscount)
usa_basemap@data$groups <- cut(usa_basemap@data$obscount, breaks=c(-1,0,5,10,20,50,100,500,2500), labels=c("0","1-5","6-10","11-20","21-50","51-100","100-500",">500"))
#convert to df for ggplot
usa_basemap@data$id = rownames(usa_basemap@data)
usa_basemap.points = fortify(usa_basemap, region="id")
usa_basemap.df = join(usa_basemap.points, usa_basemap@data, by="id")
#plot species per state vs. tweets
map_obsvstweets <- ggplot() +  
  geom_polygon(data = usa_basemap.df, aes(long, lat, group = group, fill = groups)) +
  borders("state", colour = "gray90", fill = NA) +
  geom_point(data = spider_tweets_sentiment, aes(x = centlongX, y = centlatY), colour = 'blue', alpha = .03) +
  theme_map() +
  scale_fill_brewer(palette="Greens") +
  labs(x = NULL, 
         y = NULL, 
         title = "Observations per state vs. spider tweets") +
  coord_sf(crs = st_crs(WGS84_proj), xlim=c(-124.7, -67.1), ylim = c(25.2, 49.4)) +   annotation_north_arrow(style = north_arrow_fancy_orienteering, location = "tr", which_north = "true") + 
  scale_size_continuous(range = c(1, 8), breaks = c(250, 500, 750, 1000)) + 
  annotation_scale(location = "br", line_width = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5), legend.title = element_blank(), legend.background=element_blank()) 
map_obsvstweets
#plot observations per state vs. positive tweets
spider_tweets_sentiment$minlongX <- as.numeric(spider_tweets_sentiment$minlongX)
spider_tweets_sentiment$maxlongX <- as.numeric(spider_tweets_sentiment$maxlongX)
spider_tweets_sentiment$minlatY <- as.numeric(spider_tweets_sentiment$minlatY)
spider_tweets_sentiment$maxlatY <- as.numeric(spider_tweets_sentiment$maxlatY)
spider_tweets_sentiment$centlongX <- (spider_tweets_sentiment$minlongX+spider_tweets_sentiment$maxlongX)/2
spider_tweets_sentiment$centlatY <- (spider_tweets_sentiment$minlatY+spider_tweets_sentiment$maxlatY)/2
spider_tweets_sentiment$lon <- spider_tweets_sentiment$centlongX
spider_tweets_sentiment$lat <- spider_tweets_sentiment$centlatY
coordinates(spider_tweets_sentiment) <- ~lon+lat
WGS84_proj = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
proj4string(spider_tweets_sentiment) <- CRS(WGS84_proj)
a <- spider_tweets_sentiment@data[order(spider_tweets_sentiment@data$stringsentiment), ]
negtweets <- a[1:1000,]
postweets <- a[43276:44275,]
remove(a)
map_obsvspostweets <- ggplot() +  
  geom_polygon(data = usa_basemap.df, aes(long, lat, group = group, fill = groups)) +
  borders("state", colour = "gray90", fill = NA) +
  geom_point(data = postweets, aes(x = centlongX, y = centlatY), colour = 'blue', alpha = .25) +
  theme_map() +
  scale_fill_brewer(palette="Greens") +
  labs(x = NULL, 
         y = NULL, 
         title = "Observations per state vs. top 1000 positive spider tweets by retweet count") +
  coord_sf(crs = st_crs(WGS84_proj), xlim=c(-124.7, -67.1), ylim = c(25.2, 49.4)) +   annotation_north_arrow(style = north_arrow_fancy_orienteering, location = "tr", which_north = "true") +
  scale_size_continuous(range = c(1, 8), breaks = c(250, 500, 750, 1000)) + 
  annotation_scale(location = "br", line_width = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5), legend.title = element_blank(), legend.background=element_blank()) 
map_obsvspostweets
#plot observations per state vs. negative tweets
map_obsvsnegtweets <- ggplot() +  
  geom_polygon(data = usa_basemap.df, aes(long, lat, group = group, fill = groups)) +
  borders("state", colour = "gray90", fill = NA) +
  geom_point(data = negtweets, aes(x = centlongX, y = centlatY), colour = 'red', alpha = .25) +
  theme_map() +
  scale_fill_brewer(palette="Greens") +
  labs(x = NULL, 
         y = NULL, 
         title = "Observations per state vs. top 1000 negative spider tweets by retweet count") +
  coord_sf(crs = st_crs(WGS84_proj), xlim=c(-124.7, -67.1), ylim = c(25.2, 49.4)) +   annotation_north_arrow(style = north_arrow_fancy_orienteering, location = "tr", which_north = "true") +
  scale_size_continuous(range = c(1, 8), breaks = c(250, 500, 750, 1000)) + 
  annotation_scale(location = "br", line_width = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5), legend.title = element_blank(), legend.background=element_blank()) 
map_obsvsnegtweets
#observations per state vs. 1000 most-retweeted tweets
a <- spider_tweets_sentiment@data[order(spider_tweets_sentiment@data$retweet_count, decreasing = TRUE), ]
mostrtedtweets <- a[1:1000,]
remove(a)
```

```{r mapspecies}
#copy counts
remove(usa_basemap)
usa_basemap <- getData('GADM', country='USA', level=1)
usa_basemap@data$stateinUSA <- usa_basemap@data$NAME_1
usa_basemap@data <- join(usa_basemap@data, speciesperstate, type="left")
usa_basemap@data$obsNA <- is.na(usa_basemap@data$count)
for(i in 1:nrow(usa_basemap@data)) {
  if(usa_basemap@data$obsNA[i] == "TRUE"){
  usa_basemap@data$count[i] <- "0"
  }
  else
  {
    i+1
  }
}
#group counts
usa_basemap@data$count <- as.numeric(usa_basemap@data$count)
usa_basemap@data$groups <- cut(usa_basemap@data$count, breaks=c(-1,0,2,5,10), labels=c("0","1-2","3-5","6-9"))
#convert to df for ggplot
usa_basemap@data$id = rownames(usa_basemap@data)
usa_basemap.points = fortify(usa_basemap, region="id")
usa_basemap.df = join(usa_basemap.points, usa_basemap@data, by="id")
#plot species per state vs. tweets
map_speciesvstweets <- ggplot() +  
  geom_polygon(data = usa_basemap.df, aes(long, lat, group = group, fill = groups)) +
  borders("state", colour = "gray90", fill = NA) +
  geom_point(data = spider_tweets_sentiment@data, aes(x = centlongX, y = centlatY), colour = 'blue', alpha = .03) +
  theme_map() +
  scale_fill_brewer(palette="Greens") +
  labs(x = NULL, 
         y = NULL, 
         title = "Species per state vs. spider tweets") +
  coord_sf(crs = st_crs(WGS84_proj), xlim=c(-124.7, -67.1), ylim = c(25.2, 49.4)) +   annotation_north_arrow(style = north_arrow_fancy_orienteering, location = "tr", which_north = "true") + 
  scale_size_continuous(range = c(1, 8), breaks = c(250, 500, 750, 1000)) + 
  annotation_scale(location = "br", line_width = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5), legend.title = element_blank(), legend.background=element_blank()) 
map_speciesvstweets
```

```{r plotobservationsandretweets}
#calculate statistics
#observations per state vs. positive retweets
obsperstate_joined <- read.csv(here::here("R_files_distribution", "obsperstate_joined.csv"))
obsperstate_joined$observations <- obsperstate_joined$normcount
obsperstate_joined <- subset(obsperstate_joined, select = -c(normcount))
mean(obsperstate_joined$observations)
posrtssum <- aggregate(retweet_count ~ stateinUSA, postweets, sum)
obsandposrts <- inner_join(obsperstate_joined, posrtssum, by="stateinUSA")
#calculate statistics
obsandposrts.lm <- lm(formula = retweet_count ~ observations,
                   data = obsandposrts)
summary(obsandposrts.lm)
mean(obsandposrts$observations)
mean(obsandposrts$retweet_count)
#get state abbreviations
usa_basemap <- getData('GADM', country='USA', level=1)
usa_basemap$stateinUSA <- usa_basemap$NAME_1
usa_basemap$stateinUSAabbr <- substring(usa_basemap$HASC_1,4,5)
usa_basemap <- subset(usa_basemap, select=c(stateinUSA, stateinUSAabbr))
obsandposrts <- left_join(obsandposrts, usa_basemap@data, by = "stateinUSA")
plotpos <- ggplot(obsandposrts, aes(x = observations, y = retweet_count)) + 
  geom_point(col="#3792cb") +
  geom_text(label=obsandposrts$stateinUSAabbr) +
  stat_smooth(method = "lm", col = "blue") +
  labs(x = "% of total observations that are medically-important", 
         y = "Retweets", 
         title = "Medically-important observations vs. 1000 most retweeted positive spider tweets") +
  annotate("text", x = 17.5, y = 55, label = "f = 0.66") +
  annotate("text", x = 17.5, y = 50, label = "p = 0.42") +
  annotate("text", x = 17.5, y = 45, label = "mean(x) = 4.04, mean(y) = 7.60")
plotpos
#observations per state vs. negative retweets
negrtssum <- aggregate(retweet_count ~ stateinUSA, negtweets, sum)
obsandnegrts <- inner_join(obsperstate_joined, negrtssum, by="stateinUSA")
#calculate statistics
obsandnegrts.aov <- aov(formula = retweet_count ~ observations,
                   data = obsandnegrts)
obsandnegrts.lm <- lm(formula = retweet_count ~ observations,
                   data = obsandnegrts)
summary(obsandnegrts.aov)
summary(obsandnegrts.lm)
mean(obsandnegrts$observations)
mean(obsandnegrts$retweet_count)
#get state abbreviations
usa_basemap <- getData('GADM', country='USA', level=1)
usa_basemap$stateinUSA <- usa_basemap$NAME_1
usa_basemap$stateinUSAabbr <- substring(usa_basemap$HASC_1,4,5)
usa_basemap <- subset(usa_basemap, select=c(stateinUSA, stateinUSAabbr))
obsandnegrts <- left_join(obsandnegrts, usa_basemap@data, by = "stateinUSA")
#plot
plotneg <- ggplot(obsandnegrts, aes(x = observations, y = retweet_count)) + 
  geom_point(col="#ffcccb") +
  geom_text(label=obsandnegrts$stateinUSAabbr) +
  stat_smooth(method = "lm", col = "red") +
  labs(x = "% of total observations that are medically-important", 
         y = "Retweets", 
         title = "Medically-important observations vs. 1000 most retweeted negative spider tweets") +
  annotate("text", x = 17.5, y = 550, label = "f = 0.05") +
  annotate("text", x = 17.5, y = 500, label = "p = 0.82") +
  annotate("text", x = 17.5, y = 450, label = "mean(x) = 4.11, mean(y) = 22.67")
plotneg
#observations per state vs. average sentiment of most-retweeted tweets
mostrtsmean <- aggregate(stringsentiment ~ stateinUSA, mostrtedtweets, mean)
obsandmostrts <- right_join(obsperstate_joined, mostrtsmean, by="stateinUSA")
for(i in 1:nrow(obsandmostrts)) {
  if(is.na(obsandmostrts$observations[i] == TRUE)){
  obsandmostrts$observations[i] <- "0"
  }
  else
  {
    i+1
  }
}
obsandmostrts$observations <- as.numeric(obsandmostrts$observations)
#calculate statistics
obsandmostrts.lm <- lm(formula = stringsentiment ~ observations,
                   data = obsandmostrts)
summary(obsandmostrts.lm)
mean(obsandmostrts$stringsentiment)
mean(obsandmostrts$observations)
#get state abbreviations
usa_basemap <- getData('GADM', country='USA', level=1)
usa_basemap$stateinUSA <- usa_basemap$NAME_1
usa_basemap$stateinUSAabbr <- substring(usa_basemap$HASC_1,4,5)
usa_basemap <- subset(usa_basemap, select=c(stateinUSA, stateinUSAabbr))
obsandmostrts <- left_join(obsandmostrts, usa_basemap@data, by = "stateinUSA")
#plot
plotmostrts <- ggplot(obsandmostrts, aes(x = observations, y = stringsentiment)) + 
  geom_point(col="#90ee90") +
  geom_text(label=obsandmostrts$stateinUSAabbr) +
  stat_smooth(method = "lm", col = "green") +
  labs(x = "% of total observations that are medically-important", 
         y = "Average sentiment", 
         title = "Medically-important observations vs. sentiment of most-retweeted spider tweets") +
  ylim(-1, 1) +
  annotate("text", x = 19, y = 0.9, label = "f = 1.19") +
  annotate("text", x = 19, y = 0.75, label = "p = 0.281") +
  annotate("text", x = 19, y = 0.60, label = "mean(x) = 3.26, mean(y) = 0.11")
plotmostrts
```
